verifyDepsBeforeRun: install

packages:
  - 'libs/**'
  - 'packages/**'
  - 'apps/*'
  - 'tools/*'
  - 'scripts/*'

allowBuilds:
  '@nestjs/core': false
  '@parcel/watcher': true
  '@swc/core': true
  esbuild: true
  less: true
  nx: true
  unrs-resolver: true
