name: 'Setup node, install dependencies and configure NX'
description: 'Setup node, install dependencies and set nx env variables'

runs:
  using: 'composite'
  steps:
    - name: Enable pnpm
      shell: bash
      run: corepack enable pnpm

    - name: Setup node
      uses: actions/setup-node@v6
      with:
        node-version-file: .tool-versions
        cache: pnpm
        registry-url: 'https://registry.npmjs.org'

    - name: Install
      shell: bash
      run: pnpm install --prefer-offline

    - name: Setup Nx
      uses: nrwl/nx-set-shas@v5
