name: 'Setup node, install dependencies and configure NX'
description: 'Setup node, install dependencies and set nx env variables'

runs:
  using: 'composite'
  steps:
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version-file: .tool-versions
        cache: npm

    - name: Install
      shell: bash
      run: npm ci --prefer-offline --no-audit --force # only allowing force due to often use nx beta versions, should be removed in actual repo

    - name: Setup Nx
      uses: nrwl/nx-set-shas@v4
