name: Authenticate GCP

runs:
  using: 'composite'
  steps:
    - uses: 'google-github-actions/auth@v2'
      with:
        project_id: 'nx-monorepo-demo-462313'
        workload_identity_provider: 'projects/607498314242/locations/global/workloadIdentityPools/github/providers/github-actions'
