name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: write
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

env:
  NX_VERBOSE_LOGGING: true

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Setup git
        id: git
        uses: ./.github/actions/setup-git

      # This enables task distribution via Nx Cloud
      # Run this command as early as possible, before dependencies are installed
      # Learn more at https://nx.dev/ci/reference/nx-cloud-cli#npx-nxcloud-startcirun
      # Uncomment this line to enable task distribution
      # - run: npx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="build"

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci --prefer-offline --no-audit
      - uses: nrwl/nx-set-shas@v4

      # Prepend any command with "nx-cloud record --" to record its logs to Nx Cloud
      # - run: npx nx-cloud record -- echo Hello World
      # Nx Affected runs only tasks affected by the changes in this PR/commit. Learn more: https://nx.dev/ci/features/affected

      - name: Build lint test affected projects
        run: npx nx affected --targets lint test build

      - name: Version
        run: |
          if [ "${{ steps.git.outputs.branch-name }}" == "main" ]; then
            npx tsx ${{ github.workspace }}/scripts/release.ts \
              --verbose \
              --changelogs true \
              --dryRun false
          else
            npx tsx ${{ github.workspace }}/scripts/release.ts \
              --verbose \
              --changelogs true \
              --preid pr-${{ steps.git.outputs.commit-sha-short }} \
              --git-tag false \
              --git-push false \
              --git-commit false \
              --dryRun false
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Containerize affected applications
        run: npx nx affected --targets docker-build --exclude-task-dependencies
