name: Npm install (issue reproduction)

on:
  push:

permissions:
  actions: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
          cache: 'npm'

      - name: Update npm version
        run: |
          npm install -g npm@11.3.0
          echo "npm version: $(npm --version)"
          echo "node version: $(node --version)"

      - name: Update version of pacakge
        run: |
          npm version minor --no-git-tag-version
          git checkout package-lock.json

      # - name: Install dependencies
      #   run: npm ci --prefer-offline --no-audit

      # - name: Version
      #   run: |
      #     npx tsx ${{ github.workspace }}/scripts/release.ts \
      #       --verbose \
      #       --changelogs true \
      #       --preid pr-${{ steps.git.outputs.commit-sha-short }} \
      #       --git-tag false \
      #       --git-push false \
      #       --git-commit false \
      #       --npm-dist-tag next \
      #       --dry-run false
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update lockfile
        run: npm install --package-lock-only

      - name: Diff lockfile
        run: |
          git status
          git --no-pager diff package-lock.json
